[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"
default-run = "run"

[[bin]]
name = "run"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[dependencies]
